In [28]:
import pandas as pd

# Load the actual dataset from a CSV file (adjust the file path to match your actual file location)
df = pd.read_csv('AIR_QUALITYF.csv')

In [24]:
df.head()

         DATE  CO_AVERAGE  NO_AVERAGE   PM2.5_AVERAGE   SO_AVERAGE
0  26/08/2020      136.92       0.3656           6.346        2.516
1  27/08/2020      135.22       0.3556           3.644        1.570
2  28/08/2020      158.32       0.5848           5.618        3.230
3  29/08/2020      196.14       0.4608           7.310        1.794
4  30/08/2020      200.98       0.2850           7.262        1.050

# Convert date into  weekly and set index to thursday to follow the data of the dataset

In [6]:
# Convert the 'DATE' column to datetime format (adjust format as needed, e.g., '%d/%m/%Y' for day/month/year)
df['DATE'] = pd.to_datetime(df['DATE'], format='%d/%m/%Y')

# Set the 'DATE' column as the index
df.set_index('DATE', inplace=True)

# Resample the data to weekly frequency, calculating the mean for each 7-day period
weekly_df = df.resample('7D', label='left', closed='left').mean()

# Reset the index so that 'DATE' becomes a column again (representing the first day of the week)
weekly_df.reset_index(inplace=True)

# Save the resulting weekly averages to a new CSV file
weekly_df.to_csv('weekly_averages.csv', index=False)

# Display the resulting weekly averages
print(weekly_df)

          DATE  CO_AVERAGE  NO_AVERAGE   PM2.5_AVERAGE   SO_AVERAGE
0   2020-08-26  190.780000     0.657686        6.620571     2.310000
1   2020-09-02  240.657143     1.257686        7.121143     2.610571
2   2020-09-09  246.574286     1.027857        9.068571     3.247714
3   2020-09-16  238.354286     1.557514       12.224857     3.837429
4   2020-09-23  251.977143     1.293429        9.475143     3.384286
..         ...         ...          ...             ...          ...
198 2024-06-12  170.148571     0.188229        5.486286     1.779429
199 2024-06-19  185.191429     0.210971        5.179429     2.071143
200 2024-06-26  227.648571     0.324400        5.677429     2.082857
201 2024-07-03  212.094286     0.228029        4.786000     1.964857
202 2024-07-10  211.350000     0.233833        9.432000     1.722000

[203 rows x 5 columns]

In [14]:

# Convert the 'DATE' column to datetime format (adjust format as needed, e.g., '%d/%m/%Y' for day/month/year)
df['DATE'] = pd.to_datetime(df['DATE'], format='%d/%m/%Y')

# Set the 'DATE' column as the index
df.set_index('DATE', inplace=True)

# Resample the data to weekly frequency, calculating the mean for each 7-day period
weekly_df = df.resample('7D', label='left', closed='left').mean()

# Reset the index so that 'DATE' becomes a column again (representing the first day of the week)
weekly_df.reset_index(inplace=True)

# Create a new column to show the beginning of the week explicitly
weekly_df['Week_Start'] = weekly_df['DATE']

# Save the resulting weekly averages to a new CSV file
weekly_df.to_csv('weekly_averagesF.csv', index=False)

# Display the resulting weekly averages with the start date column
print(weekly_df)

          DATE  CO_AVERAGE  NO_AVERAGE   PM2.5_AVERAGE   SO_AVERAGE   \
0   2020-08-26  190.780000     0.657686        6.620571     2.310000
1   2020-09-02  240.657143     1.257686        7.121143     2.610571
2   2020-09-09  246.574286     1.027857        9.068571     3.247714
3   2020-09-16  238.354286     1.557514       12.224857     3.837429
4   2020-09-23  251.977143     1.293429        9.475143     3.384286
..         ...         ...          ...             ...          ...
198 2024-06-12  170.148571     0.188229        5.486286     1.779429
199 2024-06-19  185.191429     0.210971        5.179429     2.071143
200 2024-06-26  227.648571     0.324400        5.677429     2.082857
201 2024-07-03  212.094286     0.228029        4.786000     1.964857
202 2024-07-10  211.350000     0.233833        9.432000     1.722000

    Week_Start
0   2020-08-26
1   2020-09-02
2   2020-09-09
3   2020-09-16
4   2020-09-23
..         ...
198 2024-06-12
199 2024-06-19
200 2024-06-26
201 2024-07-03
202 2024-07-10

[203 rows x 6 columns]

In [18]:
df

            CO_AVERAGE  NO_AVERAGE   PM2.5_AVERAGE   SO_AVERAGE
DATE
2020-08-26      136.92       0.3656           6.346        2.516
2020-08-27      135.22       0.3556           3.644        1.570
2020-08-28      158.32       0.5848           5.618        3.230
2020-08-29      196.14       0.4608           7.310        1.794
2020-08-30      200.98       0.2850           7.262        1.050
...                ...          ...             ...          ...
2024-07-11      166.90       0.1336           9.548        2.224
2024-07-12      185.20       0.1142           9.990        1.082
2024-07-13      220.48       0.1816           8.122        1.172
2024-07-14      211.24       0.4206           7.132        1.388
2024-07-15      248.04       0.3928          11.928        2.438

[1420 rows x 4 columns]

In [30]:


# Convert the 'DATE' column to datetime format (adjust format as needed, e.g., '%d/%m/%Y' for day/month/year)
df['DATE'] = pd.to_datetime(df['DATE'], format='%d/%m/%Y')

# Set the 'DATE' column as the index
df.set_index('DATE', inplace=True)

# Resample the data to weekly frequency starting from the nearest Thursday (weekday=3 represents Thursday)
# 'W-THU' ensures the week starts on Thursday
weekly_df = df.resample('W-THU').mean()

# Reset the index so that 'DATE' becomes a column again (representing the first day of the week)
weekly_df.reset_index(inplace=True)

# Rename the 'DATE' column to 'Week_Start' for clarity
weekly_df.rename(columns={'DATE': 'Week_Start'}, inplace=True)

# Save the resulting weekly averages to a new CSV file
weekly_df.to_csv('weekly_averages_thursday_start.csv', index=False)

# Display the resulting weekly averages with the Thursday start date
print(weekly_df)

    Week_Start  CO_AVERAGE  NO_AVERAGE   PM2.5_AVERAGE   SO_AVERAGE
0   2020-08-27  136.070000     0.360600        4.995000     2.043000
1   2020-09-03  221.505714     0.987229        7.718000     2.646286
2   2020-09-10  244.677143     1.086429        6.626000     2.232857
3   2020-09-17  239.071429     1.218400       10.940286     3.759714
4   2020-09-24  247.677143     1.442314       11.154571     3.738857
..         ...         ...          ...             ...          ...
199 2024-06-20  173.231429     0.194743        6.124571     1.996857
200 2024-06-27  190.740000     0.233429        4.631429     1.966571
201 2024-07-04  234.791429     0.316657        5.722286     1.929714
202 2024-07-11  203.965714     0.202571        6.187143     2.112286
203 2024-07-18  216.240000     0.277300        9.293000     1.520000

[204 rows x 5 columns]

In [1]:
import pandas as pd

# Load your CSV file
df = pd.read_csv('weekly_averages_thursday_start.csv')

# Save the DataFrame to an Excel file
df.to_excel('weeklything.xlsx', index=False)

print("CSV has been converted to Excel successfully!")

CSV has been converted to Excel successfully!

In [2]:
import pandas as pd

# Load the actual dataset from a CSV file (adjust the file path to match your actual file location)
df1 = pd.read_csv('POWER_east_england1.csv')

In [4]:
df1.head()

   YEAR  MO  DY     Date    T2M  QV2M  PRECTOTCORR  WS10M_RANGE      PS
0  2015   1   1  2015/1/1  7.02  5.86         0.83         6.38  101.99
1  2015   1   2  2015/1/2  6.43  4.94         0.35         8.40  102.11
2  2015   1   3  2015/1/3  2.75  4.39        12.80         1.98  101.71
3  2015   1   4  2015/1/4 -0.44  3.54         0.12         1.86  102.78
4  2015   1   5  2015/1/5  5.39  5.43         0.46         1.65  102.20

In [16]:
# Convert the 'DATE' column to datetime format (adjust format as needed, e.g., '%d/%m/%Y' for day/month/year)
df1['Date '] = pd.to_datetime(df1['Date '], format='%Y/%m/%d')

# Set the 'DATE' column as the index
df1.set_index('Date ', inplace=True)

# Resample the data to weekly frequency starting from the nearest Thursday (weekday=3 represents Thursday)
# 'W-THU' ensures the week starts on Thursday
weekly_df1 = df1.resample('W-THU').mean()

# Reset the index so that 'DATE' becomes a column again (representing the first day of the week)
weekly_df1.reset_index(inplace=True)

# Rename the 'DATE' column to 'Week_Start' for clarity
weekly_df1.rename(columns={'Date ': 'Week_Start'}, inplace=True)

# Save the resulting weekly averages to a new CSV file
weekly_df1.to_csv('east_england.csv', index=False)

# Display the resulting weekly averages with the Thursday start date
print(weekly_df1)

    Week_Start     YEAR     MO     DY       T2M      QV2M  PRECTOTCORR  \
0   2015-01-01  2015.00   1.00   1.00  7.020000  5.860000     0.830000
1   2015-01-08  2015.00   1.00   5.00  4.485714  4.960000     3.141429
2   2015-01-15  2015.00   1.00  12.00  6.841429  5.518571     3.662857
3   2015-01-22  2015.00   1.00  19.00  0.715714  3.760000     1.140000
4   2015-01-29  2015.00   1.00  26.00  3.180000  4.368571     1.575714
..         ...      ...    ...    ...       ...       ...          ...
466 2023-12-07  2023.00  12.00   4.00  2.817143  4.525714     4.380000
467 2023-12-14  2023.00  12.00  11.00  7.092857  6.034286     3.711429
468 2023-12-21  2023.00  12.00  18.00  7.994286  6.172857     2.721429
469 2023-12-28  2023.00  12.00  25.00  9.440000  6.677143     1.987143
470 2024-01-04  2023.25   9.25  22.75  7.685000  6.087500     5.107500

     WS10M_RANGE          PS
0       6.380000  101.990000
1       4.128571  101.887143
2       6.797143  100.075714
3       4.071429  100.511429
4       4.537143  100.935714
..           ...         ...
466     3.421429  100.302857
467     5.892857   99.654286
468     2.908571  101.792857
469     4.548571  100.127143
470     6.710000   99.290000

[471 rows x 9 columns]

In [12]:
print(df1.columns)

Index(['YEAR', 'MO', 'DY', 'Date ', 'T2M', 'QV2M', 'PRECTOTCORR',
       'WS10M_RANGE', 'PS'],
      dtype='object')

In [22]:
import pandas as pd

# Load the actual dataset from a CSV file (adjust the file path to match your actual file location)
df2 = pd.read_csv('POWER_london1.csv')
df2.head()

   YEAR  MO  DY      DATE   T2M  QV2M  PRECTOTCORR  WS10M_RANGE      PS
0  2015   1   1  2015/1/1  7.34  6.04         0.77         6.04  101.81
1  2015   1   2  2015/1/2  6.47  5.13         0.47         8.51  101.95
2  2015   1   3  2015/1/3  3.40  4.70        13.37         5.02  101.38
3  2015   1   4  2015/1/4  0.48  3.78         0.10         1.70  102.50
4  2015   1   5  2015/1/5  5.87  5.68         0.41         1.70  101.90

In [24]:
# Convert the 'DATE' column to datetime format (adjust format as needed, e.g., '%d/%m/%Y' for day/month/year)
df2['DATE'] = pd.to_datetime(df2['DATE'], format='%Y/%m/%d')

# Set the 'DATE' column as the index
df2.set_index('DATE', inplace=True)

# Resample the data to weekly frequency starting from the nearest Thursday (weekday=3 represents Thursday)
# 'W-THU' ensures the week starts on Thursday
weekly_df2 = df2.resample('W-THU').mean()

# Reset the index so that 'DATE' becomes a column again (representing the first day of the week)
weekly_df2.reset_index(inplace=True)

# Rename the 'DATE' column to 'Week_Start' for clarity
weekly_df2.rename(columns={'Date ': 'Week_Start'}, inplace=True)

# Save the resulting weekly averages to a new CSV file
weekly_df2.to_csv('London.csv', index=False)

# Display the resulting weekly averages with the Thursday start date
print(weekly_df2)

          DATE     YEAR     MO     DY       T2M      QV2M  PRECTOTCORR  \
0   2015-01-01  2015.00   1.00   1.00  7.340000  6.040000     0.770000
1   2015-01-08  2015.00   1.00   5.00  4.918571  5.171429     3.572857
2   2015-01-15  2015.00   1.00  12.00  6.990000  5.658571     4.460000
3   2015-01-22  2015.00   1.00  19.00  0.640000  3.802857     1.164286
4   2015-01-29  2015.00   1.00  26.00  3.180000  4.430000     1.372857
..         ...      ...    ...    ...       ...       ...          ...
466 2023-12-07  2023.00  12.00   4.00  2.885714  4.611429     4.181429
467 2023-12-14  2023.00  12.00  11.00  7.344286  6.208571     3.738571
468 2023-12-21  2023.00  12.00  18.00  8.087143  6.287143     2.278571
469 2023-12-28  2023.00  12.00  25.00  9.511429  6.835714     1.831429
470 2024-01-04  2023.25   9.25  22.75  7.990000  6.270000     5.375000

     WS10M_RANGE          PS
0       6.040000  101.810000
1       4.782857  101.638571
2       6.491429   99.924286
3       4.060000  100.215714
4       4.392857  100.748571
..           ...         ...
466     3.497143   99.975714
467     5.540000   99.440000
468     2.682857  101.622857
469     4.562857   99.971429
470     6.942500   99.070000

[471 rows x 9 columns]

In [34]:
import pandas as pd

# Load the actual dataset from a CSV file (adjust the file path to match your actual file location)
df3 = pd.read_csv('POWER_midland1.csv')
# Convert the 'DATE' column to datetime format (adjust format as needed, e.g., '%d/%m/%Y' for day/month/year)
df3['DATE'] = pd.to_datetime(df3['DATE'], format='%Y/%m/%d')

# Set the 'DATE' column as the index
df3.set_index('DATE', inplace=True)

# Resample the data to weekly frequency starting from the nearest Thursday (weekday=3 represents Thursday)
# 'W-THU' ensures the week starts on Thursday
weekly_df3 = df3.resample('W-THU').mean()

# Reset the index so that 'DATE' becomes a column again (representing the first day of the week)
weekly_df3.reset_index(inplace=True)

# Rename the 'DATE' column to 'Week_Start' for clarity
weekly_df3.rename(columns={'Date ': 'Week_Start'}, inplace=True)

# Save the resulting weekly averages to a new CSV file
weekly_df3.to_csv('midlands.csv', index=False)

# Display the resulting weekly averages with the Thursday start date
print(weekly_df3)

          DATE     YEAR     MO     DY       T2M      QV2M  PRECTOTCORR  \
0   2015-01-01  2015.00   1.00   1.00  6.340000  5.680000     1.330000
1   2015-01-08  2015.00   1.00   5.00  4.051429  4.768571     2.090000
2   2015-01-15  2015.00   1.00  12.00  6.505714  5.405714     3.890000
3   2015-01-22  2015.00   1.00  19.00  0.371429  3.625714     0.892857
4   2015-01-29  2015.00   1.00  26.00  2.817143  4.282857     1.824286
..         ...      ...    ...    ...       ...       ...          ...
466 2023-12-07  2023.00  12.00   4.00  2.875714  4.385714     4.801429
467 2023-12-14  2023.00  12.00  11.00  6.894286  5.947143     3.687143
468 2023-12-21  2023.00  12.00  18.00  7.847143  6.121429     3.521429
469 2023-12-28  2023.00  12.00  25.00  9.200000  6.584286     2.381429
470 2024-01-04  2023.25   9.25  22.75  7.057500  5.905000     4.405000

     WS10M_RANGE          PS
0       6.620000  102.080000
1       4.594286  102.025714
2       6.288571  100.121429
3       3.890000  100.724286
4       4.788571  101.032857
..           ...         ...
466     3.372857  100.548571
467     6.225714   99.785714
468     3.318571  101.862857
469     5.204286  100.184286
470     6.767500   99.420000

[471 rows x 9 columns]

In [38]:
# Load the actual dataset from a CSV file (adjust the file path to match your actual file location)
df5 = pd.read_csv('POWER_south_england_southhampton1.csv')
# Convert the 'DATE' column to datetime format (adjust format as needed, e.g., '%d/%m/%Y' for day/month/year)
df5['DATE'] = pd.to_datetime(df5['DATE'], format='%Y/%m/%d')

# Set the 'DATE' column as the index
df5.set_index('DATE', inplace=True)

# Resample the data to weekly frequency starting from the nearest Thursday (weekday=3 represents Thursday)
# 'W-THU' ensures the week starts on Thursday
weekly_df5 = df5.resample('W-THU').mean()

# Reset the index so that 'DATE' becomes a column again (representing the first day of the week)
weekly_df5.reset_index(inplace=True)

# Rename the 'DATE' column to 'Week_Start' for clarity
weekly_df5.rename(columns={'Date ': 'Week_Start'}, inplace=True)

# Save the resulting weekly averages to a new CSV file
weekly_df5.to_csv('south_england.csv', index=False)

# Display the resulting weekly averages with the Thursday start date
print(weekly_df5)

          DATE     YEAR     MO     DY       T2M      QV2M  PRECTOTCORR  \
0   2015-01-01  2015.00   1.00   1.00  8.940000  6.650000     2.160000
1   2015-01-08  2015.00   1.00   5.00  6.244286  5.571429     3.892857
2   2015-01-15  2015.00   1.00  12.00  7.350000  5.875714     6.174286
3   2015-01-22  2015.00   1.00  19.00  1.864286  4.062857     1.675714
4   2015-01-29  2015.00   1.00  26.00  3.898571  4.690000     0.951429
..         ...      ...    ...    ...       ...       ...          ...
466 2023-12-07  2023.00  12.00   4.00  4.151429  5.002857     6.508571
467 2023-12-14  2023.00  12.00  11.00  8.074286  6.487143     4.368571
468 2023-12-21  2023.00  12.00  18.00  8.507143  6.522857     2.072857
469 2023-12-28  2023.00  12.00  25.00  9.790000  7.064286     2.548571
470 2024-01-04  2023.25   9.25  22.75  8.512500  6.562500     7.772500

     WS10M_RANGE          PS
0       5.840000  101.990000
1       5.317143  101.812857
2       6.782857  100.197143
3       3.871429  100.342857
4       4.195714  101.011429
..           ...         ...
466     4.762857  100.057143
467     5.772857   99.655714
468     2.757143  101.894286
469     4.757143  100.245714
470     7.437500   99.247500

[471 rows x 9 columns]

In [40]:
# Load the actual dataset from a CSV file (adjust the file path to match your actual file location)
df6 = pd.read_csv('POWER_north_england_leeds1.csv')
# Convert the 'DATE' column to datetime format (adjust format as needed, e.g., '%d/%m/%Y' for day/month/year)
df6['DATE'] = pd.to_datetime(df6['DATE'], format='%Y/%m/%d')

# Set the 'DATE' column as the index
df6.set_index('DATE', inplace=True)

# Resample the data to weekly frequency starting from the nearest Thursday (weekday=3 represents Thursday)
# 'W-THU' ensures the week starts on Thursday
weekly_df6 = df6.resample('W-THU').mean()

# Reset the index so that 'DATE' becomes a column again (representing the first day of the week)
weekly_df6.reset_index(inplace=True)

# Rename the 'DATE' column to 'Week_Start' for clarity
weekly_df6.rename(columns={'Date ': 'Week_Start'}, inplace=True)

# Save the resulting weekly averages to a new CSV file
weekly_df6.to_csv('north_england.csv', index=False)

# Display the resulting weekly averages with the Thursday start date
print(weekly_df6)

          DATE     YEAR     MO     DY       T2M      QV2M  PRECTOTCORR  \
0   2015-01-01  2015.00   1.00   1.00  9.390000  6.900000     1.490000
1   2015-01-08  2015.00   1.00   5.00  3.481429  4.550000     0.781429
2   2015-01-15  2015.00   1.00  12.00  5.037143  4.788571     1.884286
3   2015-01-22  2015.00   1.00  19.00  0.298571  3.697143     1.207143
4   2015-01-29  2015.00   1.00  26.00  2.780000  4.375714     1.281429
..         ...      ...    ...    ...       ...       ...          ...
466 2023-12-07  2023.00  12.00   4.00  1.060000  3.958571     6.207143
467 2023-12-14  2023.00  12.00  11.00  5.044286  5.371429     3.717143
468 2023-12-21  2023.00  12.00  18.00  8.190000  6.225714     0.795714
469 2023-12-28  2023.00  12.00  25.00  8.032857  6.162857     4.977143
470 2024-01-04  2023.25   9.25  22.75  5.657500  5.432500     8.947500

     WS10M_RANGE          PS
0       7.380000  100.660000
1       4.847143  101.127143
2       6.115714   98.998571
3       3.820000  100.035714
4       4.848571  100.210000
..           ...         ...
466     3.515714  100.010000
467     6.404286   99.092857
468     4.017143  100.975714
469     6.447143   99.204286
470     5.952500   98.380000

[471 rows x 9 columns]

In [42]:
# Load the actual dataset from a CSV file (adjust the file path to match your actual file location)
df7 = pd.read_csv('POWER_east_englandF.csv')
# Convert the 'DATE' column to datetime format (adjust format as needed, e.g., '%d/%m/%Y' for day/month/year)
df7['DATE'] = pd.to_datetime(df7['DATE'], format='%Y/%m/%d')

# Set the 'DATE' column as the index
df7.set_index('DATE', inplace=True)

# Resample the data to weekly frequency starting from the nearest Thursday (weekday=3 represents Thursday)
# 'W-THU' ensures the week starts on Thursday
weekly_df7 = df7.resample('W-THU').mean()

# Reset the index so that 'DATE' becomes a column again (representing the first day of the week)
weekly_df7.reset_index(inplace=True)

# Rename the 'DATE' column to 'Week_Start' for clarity
weekly_df7.rename(columns={'Date ': 'Week_Start'}, inplace=True)

# Save the resulting weekly averages to a new CSV file
weekly_df7.to_csv('east_englandF.csv', index=False)

# Display the resulting weekly averages with the Thursday start date
print(weekly_df7)

          DATE     YEAR     MO     DY       T2M      QV2M  PRECTOTCORR  \
0   2015-01-01  2015.00   1.00   1.00  7.020000  5.860000     0.830000
1   2015-01-08  2015.00   1.00   5.00  4.485714  4.960000     3.141429
2   2015-01-15  2015.00   1.00  12.00  6.841429  5.518571     3.662857
3   2015-01-22  2015.00   1.00  19.00  0.715714  3.760000     1.140000
4   2015-01-29  2015.00   1.00  26.00  3.180000  4.368571     1.575714
..         ...      ...    ...    ...       ...       ...          ...
466 2023-12-07  2023.00  12.00   4.00  2.817143  4.525714     4.380000
467 2023-12-14  2023.00  12.00  11.00  7.092857  6.034286     3.711429
468 2023-12-21  2023.00  12.00  18.00  7.994286  6.172857     2.721429
469 2023-12-28  2023.00  12.00  25.00  9.440000  6.677143     1.987143
470 2024-01-04  2023.25   9.25  22.75  7.685000  6.087500     5.107500

     WS10M_RANGE          PS
0       6.380000  101.990000
1       4.128571  101.887143
2       6.797143  100.075714
3       4.071429  100.511429
4       4.537143  100.935714
..           ...         ...
466     3.421429  100.302857
467     5.892857   99.654286
468     2.908571  101.792857
469     4.548571  100.127143
470     6.710000   99.290000

[471 rows x 9 columns]

In [44]:
import pandas as pd
import glob
import os

def load_and_average_temperature(file_path_pattern):
    # Get all the CSV files matching the pattern
    all_files = glob.glob(file_path_pattern)
    
    # List to store DataFrames from each file
    data_frames = []
    
    # Loop through each file and read it into a DataFrame
    for file in all_files:
        # Read the CSV file
        dg = pd.read_csv(file, parse_dates=['DATE'])  # Assuming 'Date' column exists
        data_frames.append(dg)
    
    # Concatenate all dataframes row-wise
    combined_df = pd.concat(data_frames)
    
    # Group by 'Date' and calculate the mean for each column
    weekly_average_df = combined_df.groupby('DATE').mean().reset_index()

    # Save the daily averages to a new CSV file
    weekly_average_df.to_csv('daily_average_temperature.csv', index=False)
    
    return weekly_average_df

# Example usage:
# Assuming your CSV files are in the folder named 'data_files/'
file_path_pattern = os.path.join('temperature', '*.csv')

# Load data and calculate daily averages across all files
weekly_average_df = load_and_average_temperature(file_path_pattern)

# Display the resulting daily averages
print(weekly_average_df)

          DATE     YEAR     MO     DY       T2M      QV2M  PRECTOTCORR  \
0   2015-01-01  2015.00   1.00   1.00  7.806000  6.226000     1.316000
1   2015-01-08  2015.00   1.00   5.00  4.636286  5.004286     2.695714
2   2015-01-15  2015.00   1.00  12.00  6.544857  5.449429     4.014286
3   2015-01-22  2015.00   1.00  19.00  0.778000  3.789714     1.216000
4   2015-01-29  2015.00   1.00  26.00  3.171143  4.429429     1.401143
..         ...      ...    ...    ...       ...       ...          ...
466 2023-12-07  2023.00  12.00   4.00  2.758000  4.496857     5.215714
467 2023-12-14  2023.00  12.00  11.00  6.890000  6.009714     3.844571
468 2023-12-21  2023.00  12.00  18.00  8.125143  6.266000     2.278000
469 2023-12-28  2023.00  12.00  25.00  9.194857  6.664857     2.745143
470 2024-01-04  2023.25   9.25  22.75  7.380500  6.051500     6.321500

     WS10M_RANGE          PS
0       6.452000  101.706000
1       4.734000  101.698286
2       6.495143   99.863429
3       3.942571  100.366000
4       4.552571  100.787714
..           ...         ...
466     3.714000  100.178857
467     5.967143   99.525714
468     3.136857  101.629714
469     5.104000   99.946571
470     6.762000   99.081500

[471 rows x 9 columns]

In [46]:
# Assuming daily_average_df is the DataFrame you already have

# Save the daily averages to a new Excel file
weekly_average_df.to_excel('weekly_average_temperature.xlsx', index=False)

print("Data saved to 'weekly_average_temperature.xlsx'")

Data saved to 'weekly_average_temperature.xlsx'

In [56]:
# Load the dataset
df = pd.read_csv('POWER_Regional_Daily.csv')

# Display the column names to verify the correct names for year, month, and day
print(df.columns)

Index(['LAT', 'LON', 'YEAR', 'MO', 'DY', 'T2M', 'QV2M', 'PRECTOTCORR',
       'WS10M_RANGE', 'PS'],
      dtype='object')

In [62]:
df

,LAT,LON,YEAR,MO,DY,T2M,QV2M,PRECTOTCORR,WS10M_RANGE,PS
0,51.25,-3.25,2024,1,11,1.16,3.91,0.02,2.77,102.38
1,51.25,-2.75,2024,1,11,0.66,3.78,0.03,2.47,102.50
2,51.25,-2.25,2024,1,11,0.36,3.69,0.05,2.28,102.48
3,51.25,-1.75,2024,1,11,0.25,3.66,0.06,2.21,102.34
4,51.25,-1.25,2024,1,11,0.51,3.75,0.08,2.13,102.50
...,...,...,...,...,...,...,...,...,...,...
16715,54.75,-0.25,2024,7,18,16.27,9.92,0.02,2.82,101.70
16716,54.75,0.25,2024,7,18,15.63,9.93,0.02,2.00,101.89
16717,54.75,0.75,2024,7,18,15.13,9.96,0.03,1.27,101.98
16718,54.75,1.25,2024,7,18,15.10,10.01,0.02,2.01,102.02
16719,54.75,1.75,2024,7,18,15.32,10.06,0.01,2.71,102.07

In [66]:
import pandas as pd

# Load the dataset
df = pd.read_csv('POWER_Regional_DailyG.csv')

# Ensure that the 'DATE' column is in datetime format
df['DATE'] = pd.to_datetime(df['DATE'], format='%d/%m/%Y')

# Sort data by date
df = df.sort_values(by='DATE')

# Set 'DATE' as index to make it easier to resample
df.set_index('DATE', inplace=True)

# Resample data by 7-day periods (starting from Thursday), taking the mean for each week
# 'W-THU' ensures the week starts on Thursday
df_weekly = df.resample('W-THU').mean()

# Save the weekly averaged data to an Excel file
df_weekly.to_excel('weekly_averages_thursday.xlsx')

print("Weekly averages (aligned with Thursdays) saved to weekly_averages_thursday.xlsx")

Weekly averages (aligned with Thursdays) saved to weekly_averages_thursday.xlsx

In [86]:
hf = pd.read_csv('fluFinal.csv')
hf1 = pd.read_csv('airqualityFinal.csv')
hf2 = pd.read_csv('weatherFinal.csv')

In [100]:
hf.head()

,Week number,DATE,A(H1N1),A(H3N2),A(unknown),B,Positivity (%)*,Influenza 2022-2023 (%),Influenza 2021-2022 (%),Influenza 2020-2021 (%),Influenza 2019-2020 (%),Influenza 2018-2019 (%),Influenza 2017-2018 (%)
0,23,2015-06-04,0,0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,40,2015-10-01,0,3,5,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,41,2015-10-08,6,2,21,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,42,2015-10-15,7,0,6,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,43,2015-10-22,6,1,5,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [94]:
hf.columns

Index(['Week number', 'DATE', 'A(H1N1)', 'A(H3N2)', 'A(unknown)', 'B',
       'Positivity (%)*', 'Influenza 2022-2023 (%)', 'Influenza 2021-2022 (%)',
       'Influenza 2020-2021 (%)', 'Influenza 2019-2020 (%)',
       'Influenza 2018-2019 (%)', 'Influenza 2017-2018 (%)'],
      dtype='object')

In [92]:
hf.columns = hf.columns.str.strip()  # This will remove any spaces around column names

In [106]:
hf1.head()

        DATE        NO    PM2.5       SO    CO
0 2015-06-04  0.001473   9.7296  0.005577  0.0
1 2015-10-01  0.005648  11.6860  0.008509  0.0
2 2015-10-08  0.005648  11.6860  0.008509  0.0
3 2015-10-15  0.005648  11.6860  0.008509  0.0
4 2015-10-22  0.005648  11.6860  0.008509  0.0

In [104]:
hf2.head()

        DATE       T2M      QV2M  PRECTOTCORR  WS10M_RANGE          PS
0 2015-06-04  7.806000  6.226000     1.316000     6.452000  101.706000
1 2015-10-01  4.636286  5.004286     2.695714     4.734000  101.698286
2 2015-10-08  6.544857  5.449429     4.014286     6.495143   99.863429
3 2015-10-15  0.778000  3.789714     1.216000     3.942571  100.366000
4 2015-10-22  3.171143  4.429429     1.401143     4.552571  100.787714

In [102]:
hf['DATE'] = pd.to_datetime(hf['DATE'], format='%d/%m/%Y')
hf1['DATE'] = pd.to_datetime(hf['DATE'], format='%d/%m/%Y')
hf2['DATE'] = pd.to_datetime(hf['DATE'], format='%d/%m/%Y')

In [108]:
import pandas as pd

# Assume 'hf', 'hf1', and 'hf2' are your three DataFrames.

# First LEFT JOIN between hf and hf1
# Replace 'common_column1' with the actual column that exists in both hf and hf1.
hf_merged_1 = pd.merge(hf, hf1, on='DATE', how='left')

# Second LEFT JOIN between the result (hf_merged_1) and hf2
# Replace 'common_column2' with the actual column that exists in both hf_merged_1 and hf2.
final_merged_result = pd.merge(hf_merged_1, hf2, on='DATE', how='left')

# Display the final result
print(final_merged_result)

     Week number       DATE  A(H1N1)  A(H3N2)  A(unknown)   B  \
0             23 2015-06-04        0        0           0   1
1             40 2015-10-01        0        3           5   6
2             41 2015-10-08        6        2          21   2
3             42 2015-10-15        7        0           6   5
4             43 2015-10-22        6        1           5   4
..           ...        ...      ...      ...         ...  ..
372           30 2024-07-25        2       36          21  11
373           31 2024-08-01        3       45          20   8
374           32 2024-08-08        1       41          12   2
375           33 2024-08-15        1       22          11   7
376           34 2024-08-22        2       18          22   3

     Positivity (%)*  Influenza 2022-2023 (%)  Influenza 2021-2022 (%)  \
0                0.0                      0.0                      0.0
1                0.0                      0.0                      0.0
2                0.0                      0.0                      0.0
3                0.0                      0.0                      0.0
4                0.0                      0.0                      0.0
..               ...                      ...                      ...
372              0.0                      0.0                      0.0
373              0.0                      0.0                      0.0
374              0.0                      0.0                      0.0
375              0.0                      0.0                      0.0
376              0.0                      0.0                      0.0

     Influenza 2020-2021 (%)  ...  Influenza 2017-2018 (%)        NO    PM2.5  \
0                        0.0  ...                      0.0  0.001473   9.7296
1                        0.0  ...                      0.0  0.005648  11.6860
2                        0.0  ...                      0.0  0.005648  11.6860
3                        0.0  ...                      0.0  0.005648  11.6860
4                        0.0  ...                      0.0  0.005648  11.6860
..                       ...  ...                      ...       ...      ...
372                      0.0  ...                      0.0       NaN      NaN
373                      0.0  ...                      0.0       NaN      NaN
374                      0.0  ...                      0.0       NaN      NaN
375                      0.0  ...                      0.0       NaN      NaN
376                      0.0  ...                      0.0       NaN      NaN

          SO    CO       T2M      QV2M  PRECTOTCORR  WS10M_RANGE          PS
0    0.005577  0.0  7.806000  6.226000     1.316000     6.452000  101.706000
1    0.008509  0.0  4.636286  5.004286     2.695714     4.734000  101.698286
2    0.008509  0.0  6.544857  5.449429     4.014286     6.495143   99.863429
3    0.008509  0.0  0.778000  3.789714     1.216000     3.942571  100.366000
4    0.008509  0.0  3.171143  4.429429     1.401143     4.552571  100.787714
..        ...  ...       ...       ...          ...          ...         ...
372       NaN  NaN  6.423714  5.379143     3.341429     5.971143   99.963143
373       NaN  NaN  6.290286  5.190857     4.202000     9.343714   99.997429
374       NaN  NaN  5.883429  5.034000     2.489714     4.580286  101.572857
375       NaN  NaN  5.830286  4.897429     1.071429     4.121429  101.281429
376       NaN  NaN  8.065714  5.850000     2.762571     4.672000  100.851429

[377 rows x 22 columns]

In [110]:
# Save the weekly averaged data to an Excel file
final_merged_result.to_excel('final_merged.xlsx')

print("final_merged.xlsx")

final_merged.xlsx

In [15]:
import pandas as pd

# Define the function to aggregate data and skip formatting issues
def aggregate_to_weekly(df):
    # Initialize a list to collect valid rows
    valid_rows = []

    # Iterate over each row to handle date and time formatting
    for index, row in df.iterrows():
        try:
            # Combine the Date and time into a DateTime column
            row['DateTime'] = pd.to_datetime(row['Date'] + ' ' + row['time'], format="%m/%d/%Y %H:%M")
            valid_rows.append(row)  # If successful, append the row to valid_rows
        except ValueError:
            # Skip any row with a formatting issue (do nothing)
            continue

    # Create a new DataFrame from valid rows
    valid_df = pd.DataFrame(valid_rows)

    # Drop unnecessary columns ('status' and 'unit')
    columns_to_keep = ['DateTime', 'Carbon monoxide', 'Nitric oxide', 'PM<sub>10</sub> particulate matter (Hourly measured)',
                       'Nitrogen dioxide', 'Nitrogen oxides as nitrogen dioxide', 'Ozone', 
                       'PM<sub>2.5</sub> particulate matter (Hourly measured)', 'Sulphur dioxide']
    valid_df = valid_df[columns_to_keep]

    # Set the DateTime as index
    valid_df.set_index('DateTime', inplace=True)

    # Resample the data to daily averages (from hourly to daily)
    daily_avg = valid_df.resample('D').mean()

    # Resample again to weekly averages and ensure weeks start on Thursday
    weekly_avg = daily_avg.resample('W-THU').mean()

    # Return the final weekly-aggregated DataFrame
    return weekly_avg

# Step 1: Read the CSV file into a DataFrame
air_data = pd.read_csv('MY1_2024.csv')

# Step 2: Call the function to aggregate data into weekly averages
weekly_avg_data = aggregate_to_weekly(air_data)

# Step 3: Save the weekly average data to a new CSV file
weekly_avg_data.to_csv('weekly_avg_air.csv')

print("Weekly average data saved as 'weekly_avg_air.csv'")

Weekly average data saved as 'weekly_avg_air.csv'

In [21]:
import pandas as pd

# Define the function to aggregate data and handle date-time formatting issues
def aggregate_to_weekly(df):
    # Try to convert the 'Date' and 'time' columns into a DateTime column, but ignore errors
    df['DateTime'] = pd.to_datetime(df['Date'] + ' ' + df['time'], format="%m/%d/%Y %H:%M", errors='coerce')

    # Drop unnecessary columns ('status' and 'unit')
    columns_to_keep = ['DateTime', 'Carbon monoxide', 'Nitric oxide', 'PM<sub>10</sub> particulate matter (Hourly measured)',
                       'Nitrogen dioxide', 'Nitrogen oxides as nitrogen dioxide', 'Ozone', 
                       'PM<sub>2.5</sub> particulate matter (Hourly measured)', 'Sulphur dioxide']
    df = df[columns_to_keep]

    # Drop rows where DateTime conversion failed (NaT values)
    valid_df = df.dropna(subset=['DateTime'])

    # Set the DateTime as index
    valid_df.set_index('DateTime', inplace=True)

    # Resample the data to daily averages (from hourly to daily)
    daily_avg = valid_df.resample('D').mean()

    # Resample again to weekly averages and ensure weeks start on Thursday
    weekly_avg = daily_avg.resample('W-THU').mean()

    # Return the final weekly-aggregated DataFrame
    return weekly_avg

# Step 1: Read the CSV file into a DataFrame
air_data = pd.read_csv('MY1_2024.csv')

# Step 2: Call the function to aggregate data into weekly averages
weekly_avg_data = aggregate_to_weekly(air_data)

# Step 3: Save the weekly average data to a new CSV file
weekly_avg_data.to_csv('weekly_avg_air1.csv')

print("Weekly average data saved as 'weekly_avg_air1.csv'")

Weekly average data saved as 'weekly_avg_air1.csv'

In [27]:
import pandas as pd

# Define the function to aggregate data and handle partial missing data
def aggregate_to_weekly(df):
    # Try to convert the 'Date' and 'time' columns into a DateTime column, skipping any issues
    df['DateTime'] = pd.to_datetime(df['Date'] + ' ' + df['time'], format="%m/%d/%Y %H:%M", errors='coerce')

    # Drop unnecessary columns ('status' and 'unit')
    columns_to_keep = ['DateTime', 'Carbon monoxide', 'Nitric oxide', 'PM<sub>10</sub> particulate matter (Hourly measured)',
                       'Nitrogen dioxide', 'Nitrogen oxides as nitrogen dioxide', 'Ozone', 
                       'PM<sub>2.5</sub> particulate matter (Hourly measured)', 'Sulphur dioxide']
    df = df[columns_to_keep]

    # Set the DateTime as index, but keep the invalid DateTime rows for further calculations
    valid_df = df.dropna(subset=['DateTime'])

    # Resample to calculate the mean for each day (it will use the available hours)
    daily_avg = valid_df.resample('D', on='DateTime').mean()

    # Resample again to weekly averages and ensure weeks start on Thursday
    weekly_avg = daily_avg.resample('W-THU').mean()

    # Restrict the output to the date range of the original data (ending at the latest valid date)
    last_valid_date = valid_df['DateTime'].max()
    weekly_avg = weekly_avg[weekly_avg.index <= last_valid_date]

    # Return the final weekly-aggregated DataFrame
    return weekly_avg

In [ ]:
# Step 1: Read the CSV file into a DataFrame
air_data = pd.read_csv('MY1_2024.csv')

# Step 2: Call the function to aggregate data into weekly averages
weekly_avg_data = aggregate_to_weekly(air_data)

# Step 3: Save the weekly average data to a new CSV file
weekly_avg_data.to_csv('weekly_avg_air.csv')

print("Weekly average data saved as 'weekly_avg_air.csv'")

In [29]:
import pandas as pd

# Step 1: Read the CSV file
# Replace 'your_file.csv' with the actual file path to your CSV
df = pd.read_csv('co2015_2019.csv')

df

            Date  Carbon monoxide
0     01/01/2015          312.588
1     02/01/2015          187.436
2     03/01/2015          374.581
3     04/01/2015          560.853
4     05/01/2015          808.537
...          ...              ...
1821  27/12/2019          132.381
1822  28/12/2019          126.288
1823  29/12/2019          140.263
1824  30/12/2019          131.323
1825  31/12/2019          210.690

[1826 rows x 2 columns]

In [35]:
# Step 2: Convert the 'DATE' column to datetime format
df['Date'] = pd.to_datetime(df['Date'], dayfirst= True)



# Step 3: Set 'DATE' as the index for resampling
df.set_index('Date', inplace=True)

# Step 4: Resample the data to get the weekly average of 'CO'
# Resample starting from Thursday ('W-THU' specifies that the week ends on Thursday)
weekly_avg = df['Carbon monoxide'].resample('W-THU').mean().reset_index()

# Step 5: Display the result
print(weekly_avg)

          Date  Carbon monoxide
0   2015-01-01       312.588000
1   2015-01-08       661.598143
2   2015-01-15       616.443857
3   2015-01-22       727.292429
4   2015-01-29       770.783429
..         ...              ...
257 2019-12-05       395.711000
258 2019-12-12       330.164714
259 2019-12-19       282.237429
260 2019-12-26       296.050286
261 2020-01-02       148.189000

[262 rows x 2 columns]

In [41]:
gf = pd.read_csv('experiment.csv')

In [43]:
gf

           Date
0    04/06/2015
1    01/10/2015
2    08/10/2015
3    15/10/2015
4    22/10/2015
..          ...
147  05/12/2019
148  12/12/2019
149  19/12/2019
150  26/12/2019
151  02/01/2020

[152 rows x 1 columns]

In [49]:
gf['Date'] = pd.to_datetime(gf['Date'], dayfirst= True)

gf_merged_1 = pd.merge(gf, weekly_avg, on='Date', how='left')


# Display the final result
print(gf_merged_1)

          Date  Carbon monoxide
0   2015-06-04       506.718000
1   2015-10-01       427.469429
2   2015-10-08       751.117143
3   2015-10-15       462.478571
4   2015-10-22       577.775857
..         ...              ...
147 2019-12-05       395.711000
148 2019-12-12       330.164714
149 2019-12-19       282.237429
150 2019-12-26       296.050286
151 2020-01-02       148.189000

[152 rows x 2 columns]

In [51]:
# Assuming daily_average_df is the DataFrame you already have

# Save the daily averages to a new Excel file
gf_merged_1.to_excel('co_merged_1.xlsx', index=False)

print("Data saved to 'co.xlsx'")

Data saved to 'co.xlsx'

In [50]:
import pandas as pd
hf = pd.read_csv('fluFinal.csv')
hf2 = pd.read_csv('AQ_merged_1.csv')
hf1 = pd.read_csv('weatherFinal - Copy.csv')

In [52]:
hf.columns = hf.columns.str.strip()

In [54]:
hf['DATE'] = pd.to_datetime(hf['DATE'], format='%d/%m/%Y')
hf1['DATE'] = pd.to_datetime(hf['DATE'], format='%d/%m/%Y')
hf2['DATE'] = pd.to_datetime(hf['DATE'], format='%d/%m/%Y')

In [44]:
hf

,Week number,DATE,A(H1N1),A(H3N2),A(unknown),B,Positivity (%)*,Influenza 2022-2023 (%),Influenza 2021-2022 (%),Influenza 2020-2021 (%),Influenza 2019-2020 (%),Influenza 2018-2019 (%),Influenza 2017-2018 (%)
0,23,2015-06-04,0,0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,40,2015-10-01,0,3,5,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,41,2015-10-08,6,2,21,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,42,2015-10-15,7,0,6,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,43,2015-10-22,6,1,5,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
372,30,2024-07-25,2,36,21,11,0.0,0.0,0.0,0.0,0.0,0.0,0.0
373,31,2024-08-01,3,45,20,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0
374,32,2024-08-08,1,41,12,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
375,33,2024-08-15,1,22,11,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0
376,34,2024-08-22,2,18,22,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [48]:
hf2

          DATE        NO      PM2.5        SO          CO
0   2015-06-04  0.001473   9.729600  0.005577  506.718000
1   2015-10-01  0.005648  11.686000  0.008509  427.469429
2   2015-10-08  0.005648  11.686000  0.008509  751.117143
3   2015-10-15  0.005648  11.686000  0.008509  462.478571
4   2015-10-22  0.005648  11.686000  0.008509  577.775857
..         ...       ...        ...       ...         ...
367 2024-06-20  0.194743   6.124571  1.996857  173.231429
368 2024-06-27  0.233429   4.631429  1.966571  190.740000
369 2024-07-04  0.316657   5.722286  1.929714  234.791429
370 2024-07-11  0.202571   6.187143  2.112286  203.965714
371 2024-07-18  0.277300   9.293000  1.520000  216.240000

[372 rows x 5 columns]

In [26]:


# Assume 'hf', 'hf1', and 'hf2' are your three DataFrames.

# First LEFT JOIN between hf and hf1
# Replace 'common_column1' with the actual column that exists in both hf and hf1.
hf_merged_1 = pd.merge(hf, hf1, on='DATE', how='left')

# Second LEFT JOIN between the result (hf_merged_1) and hf2
# Replace 'common_column2' with the actual column that exists in both hf_merged_1 and hf2.
Merge_A = pd.merge(hf_merged_1, hf2, on='DATE', how='left')

# Display the final result
print(Merge_A)

     Week number       DATE  A(H1N1)  A(H3N2)  A(unknown)   B  \
0             23 2015-06-04        0        0           0   1
1             40 2015-10-01        0        3           5   6
2             41 2015-10-08        6        2          21   2
3             42 2015-10-15        7        0           6   5
4             43 2015-10-22        6        1           5   4
..           ...        ...      ...      ...         ...  ..
372           30 2024-07-25        2       36          21  11
373           31 2024-08-01        3       45          20   8
374           32 2024-08-08        1       41          12   2
375           33 2024-08-15        1       22          11   7
376           34 2024-08-22        2       18          22   3

     Positivity (%)*  Influenza 2022-2023 (%)  Influenza 2021-2022 (%)  \
0                0.0                      0.0                      0.0
1                0.0                      0.0                      0.0
2                0.0                      0.0                      0.0
3                0.0                      0.0                      0.0
4                0.0                      0.0                      0.0
..               ...                      ...                      ...
372              0.0                      0.0                      0.0
373              0.0                      0.0                      0.0
374              0.0                      0.0                      0.0
375              0.0                      0.0                      0.0
376              0.0                      0.0                      0.0

     Influenza 2020-2021 (%)  ...  Influenza 2017-2018 (%)        T2M  \
0                        0.0  ...                      0.0  11.946286
1                        0.0  ...                      0.0  11.740286
2                        0.0  ...                      0.0  12.106857
3                        0.0  ...                      0.0   9.672000
4                        0.0  ...                      0.0  10.287143
..                       ...  ...                      ...        ...
372                      0.0  ...                      0.0  10.634571
373                      0.0  ...                      0.0  10.177714
374                      0.0  ...                      0.0   6.863714
375                      0.0  ...                      0.0   6.918857
376                      0.0  ...                      0.0   3.235143

         QV2M  PRECTOTCORR  WS10M_RANGE          PS        NO    PM2.5  \
0    6.570571     2.505714     6.024857  100.493714  0.001473   9.7296
1    6.937143     0.078857     2.657714  102.480000  0.005648  11.6860
2    7.811714     3.934857     3.706857  100.503714  0.005648  11.6860
3    6.202857     0.484286     3.170000  101.436286  0.005648  11.6860
4    6.838571     1.617714     3.145143  101.372000  0.005648  11.6860
..        ...          ...          ...         ...       ...      ...
372  7.442571     3.724857     4.097714   99.903143       NaN      NaN
373  7.508857     4.726000     4.798571   99.877143       NaN      NaN
374  5.904857     4.597429     5.259429   99.144000       NaN      NaN
375  5.946571     2.091143     3.901714  101.099429       NaN      NaN
376  4.497429     0.529143     2.081714  101.304000       NaN      NaN

           SO          CO
0    0.005577  506.718000
1    0.008509  427.469429
2    0.008509  751.117143
3    0.008509  462.478571
4    0.008509  577.775857
..        ...         ...
372       NaN         NaN
373       NaN         NaN
374       NaN         NaN
375       NaN         NaN
376       NaN         NaN

[377 rows x 22 columns]

In [58]:
hf1

          DATE        T2M       QV2M  PRECTOTCORR  WS10M_RANGE          PS
0   2015-06-04  11.946286   6.570571     2.505714     6.024857  100.493714
1   2015-10-01  11.740286   6.937143     0.078857     2.657714  102.480000
2   2015-10-08  12.106857   7.811714     3.934857     3.706857  100.503714
3   2015-10-15   9.672000   6.202857     0.484286     3.170000  101.436286
4   2015-10-22  10.287143   6.838571     1.617714     3.145143  101.372000
..         ...        ...        ...          ...          ...         ...
456        NaT  13.256786   7.896705     2.124140     3.978214   99.964123
457        NaT  16.717419   9.859756     0.400032     3.496461  100.455179
458        NaT  13.947321   8.123555     1.976169     4.243409  100.288555
459        NaT  14.340097   8.745812     6.230974     4.486705   99.996721
460        NaT  17.872841  10.548295     0.088182     2.674659  101.024546

[461 rows x 6 columns]

In [30]:
Merge_A.to_excel('Merge_A.xlsx')

print("Merge_A.xlsx")

Merge_A.xlsx

In [15]:
hf_merged_1 = pd.merge(hf1, hf, on='DATE', how='left')

# Second LEFT JOIN between the result (hf_merged_1) and hf2
# Replace 'common_column2' with the actual column that exists in both hf_merged_1 and hf2.
Merge_B = pd.merge(hf_merged_1, hf2, on='DATE', how='left')

# Display the final result
print(Merge_B)

          DATE        T2M       QV2M  PRECTOTCORR  WS10M_RANGE          PS  \
0   2015-06-04   7.806000   6.226000     1.316000     6.452000  101.706000
1   2015-10-01   4.636286   5.004286     2.695714     4.734000  101.698286
2   2015-10-08   6.544857   5.449429     4.014286     6.495143   99.863429
3   2015-10-15   0.778000   3.789714     1.216000     3.942571  100.366000
4   2015-10-22   3.171143   4.429429     1.401143     4.552571  100.787714
..         ...        ...        ...          ...          ...         ...
494        NaT  13.256786   7.896705     2.124140     3.978214   99.964123
495        NaT  16.717419   9.859756     0.400032     3.496461  100.455179
496        NaT  13.947321   8.123555     1.976169     4.243409  100.288555
497        NaT  14.340097   8.745812     6.230974     4.486705   99.996721
498        NaT  17.872841  10.548295     0.088182     2.674659  101.024546

     Week number  A(H1N1)  A(H3N2)  A(unknown)  ...  Influenza 2022-2023 (%)  \
0           23.0      0.0      0.0         0.0  ...                      0.0
1           40.0      0.0      3.0         5.0  ...                      0.0
2           41.0      6.0      2.0        21.0  ...                      0.0
3           42.0      7.0      0.0         6.0  ...                      0.0
4           43.0      6.0      1.0         5.0  ...                      0.0
..           ...      ...      ...         ...  ...                      ...
494          NaN      NaN      NaN         NaN  ...                      NaN
495          NaN      NaN      NaN         NaN  ...                      NaN
496          NaN      NaN      NaN         NaN  ...                      NaN
497          NaN      NaN      NaN         NaN  ...                      NaN
498          NaN      NaN      NaN         NaN  ...                      NaN

     Influenza 2021-2022 (%)  Influenza 2020-2021 (%)  \
0                        0.0                      0.0
1                        0.0                      0.0
2                        0.0                      0.0
3                        0.0                      0.0
4                        0.0                      0.0
..                       ...                      ...
494                      NaN                      NaN
495                      NaN                      NaN
496                      NaN                      NaN
497                      NaN                      NaN
498                      NaN                      NaN

     Influenza 2019-2020 (%)  Influenza 2018-2019 (%)  \
0                        0.0                      0.0
1                        0.0                      0.0
2                        0.0                      0.0
3                        0.0                      0.0
4                        0.0                      0.0
..                       ...                      ...
494                      NaN                      NaN
495                      NaN                      NaN
496                      NaN                      NaN
497                      NaN                      NaN
498                      NaN                      NaN

     Influenza 2017-2018 (%)        NO    PM2.5        SO          CO
0                        0.0  0.001473   9.7296  0.005577  506.718000
1                        0.0  0.005648  11.6860  0.008509  427.469429
2                        0.0  0.005648  11.6860  0.008509  751.117143
3                        0.0  0.005648  11.6860  0.008509  462.478571
4                        0.0  0.005648  11.6860  0.008509  577.775857
..                       ...       ...      ...       ...         ...
494                      NaN       NaN      NaN       NaN         NaN
495                      NaN       NaN      NaN       NaN         NaN
496                      NaN       NaN      NaN       NaN         NaN
497                      NaN       NaN      NaN       NaN         NaN
498                      NaN       NaN      NaN       NaN         NaN

[499 rows x 22 columns]

In [36]:
Merge_B.to_csv('Merge_B.csv')

print("Merge_B.csv")

Merge_B.csv